//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.Umbraco.MediaSync.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExampleValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExampleValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.Umbraco.MediaSync.Tests.ExampleValues", typeof(ExampleValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;1 column layout&quot;,
        ///  &quot;sections&quot;: [
        ///    {
        ///      &quot;grid&quot;: 12,
        ///      &quot;rows&quot;: [
        ///        {
        ///          &quot;name&quot;: &quot;Content&quot;,
        ///          &quot;areas&quot;: [
        ///            {
        ///              &quot;grid&quot;: 12,
        ///              &quot;allowAll&quot;: false,
        ///              &quot;allowed&quot;: [
        ///                &quot;rte&quot;
        ///              ],
        ///              &quot;hasConfig&quot;: false,
        ///              &quot;controls&quot;: [
        ///                {
        ///                  &quot;value&quot;: &quot;&lt;p&gt;More content &lt;a data-udi=\&quot;umb://media/cee5459177ba48fd8db8739d2a1cc8d0\&quot; href=\&quot;/media/1001/this [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GridJsonWithHtmlLink {
            get {
                return ResourceManager.GetString("GridJsonWithHtmlLink", resourceCulture);
            }
        }
    }
}
